In [1]:
import numpy as np
import pandas as pd
import folium
from folium.plugins import HeatMap
import pandas as pd
from argparse import ArgumentParser
from tqdm import tqdm

In [4]:
chl_df = pd.read_csv('chl.csv')
chl_df["Time"] = pd.to_datetime(chl_df['Time'])
geometry = [list(map(float, x.split(','))) for x in chl_df.AOI]
lat = pd.Series([x[0] for x in geometry])
lon = pd.Series([x[1] for x in geometry])
chl_df['latitude'] = lat
chl_df['longitude'] = lon
chl_df['latitude']=pd.to_numeric(chl_df['latitude'])
chl_df['longitude']=pd.to_numeric(chl_df['longitude'])
chl_df['Measurement Value']=pd.to_numeric(chl_df['Measurement Value'])
chl_df = chl_df[chl_df['Measurement Value'].notna()]
chl_df.rename(columns = {'Measurement Value':'Chl_concentration'}, inplace = True)
chl_df = chl_df[['Time', 'Country', 'Region', 'Chl_concentration', 'latitude', 'longitude']]

In [6]:
chl_df

,Time,Country,Region,Chl_concentration,latitude,longitude
1,2019-01-11 12:40:00,IT,North Adriatic Sea,-43.211117,45.314247,12.508055
3,2019-01-25 12:20:00,IT,North Adriatic Sea,-27.113966,45.314247,12.508055
6,2019-02-15 12:40:00,IT,North Adriatic Sea,0.000000,45.314247,12.508055
7,2019-02-22 11:40:00,IT,North Adriatic Sea,-29.437669,45.314247,12.508055
8,2019-02-28 12:10:00,IT,North Adriatic Sea,56.445046,45.314247,12.508055
...,...,...,...,...,...,...
1333,2021-05-01 18:20:00,US,New York,22.262022,41.101700,-72.935000
1334,2021-05-08 18:20:00,US,New York,-11.593908,41.101700,-72.935000
1335,2021-05-15 18:20:00,US,New York,-23.235385,41.101700,-72.935000
1338,2021-06-05 18:20:00,US,New York,-27.664935,41.101700,-72.935000
1339,2021-06-12 18:20:00,US,New York,-7.542258,41.101700,-72.935000

In [8]:
venice_chl_df = chl_df.loc[chl_df['Country'] == "JP"]
venice_chl_df

          Time Country     Region  Chl_concentration  latitude   longitude
238 2019-01-05      JP  Tokyo Bay              17.62     35.55  139.900000
239 2019-01-12      JP  Tokyo Bay             -17.19     35.55  139.900000
240 2019-01-19      JP  Tokyo Bay              69.90     35.55  139.900000
241 2019-01-26      JP  Tokyo Bay             115.04     35.55  139.900000
242 2019-02-02      JP  Tokyo Bay              37.20     35.55  139.900000
..         ...     ...        ...                ...       ...         ...
964 2021-04-17      JP  Tokyo Bay             -18.15     35.55  139.900001
965 2021-04-24      JP  Tokyo Bay               5.02     35.55  139.900001
966 2021-05-01      JP  Tokyo Bay             282.04     35.55  139.900001
967 2021-05-08      JP  Tokyo Bay              -4.78     35.55  139.900001
968 2021-05-29      JP  Tokyo Bay             -38.92     35.55  139.900001

[619 rows x 6 columns]

In [15]:
df = df.drop_duplicates(subset = ["latitude"])

In [13]:
df

,AOI,Country,Region,City,Site Name,Description,Method,EO Sensor,Input Data,Indicator code,Time,Measurement Value,Y axis,Indicator Name,Data Provider,AOI_ID,Update Frequency,latitude,longitude
1,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, Chl-a",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,Aqua MODIS,MODISA L2 LAC OC,N3b,2019-01-11T12:40:00,-43.211117,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,IT6,Weekly,45.314247,12.508055
238,"35.550000,139.900000",JP,Tokyo Bay,"Tokyo, Chl-a",North part of Tokyo Bay,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,GCOM-C/SGLI,EORC product,N3b,2019-01-05T00:00:00,17.620000,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,JAXA/EORC,JP01,Weekly,35.550000,139.900000
332,"34.550000,135.150000",JP,Osaka Bay,"Osaka, Chl-a",Offshore Kobe in the Osaka Bay,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,GCOM-C/SGLI,EORC product,N3b,2019-01-05T00:00:00,-10.740000,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,JAXA/EORC,JP02,Weekly,34.550000,135.150000
439,"34.750000,136.700000",JP,Ise Bay,"Ise Bay, Chl-a",Center of Ise Bay,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,GCOM-C/SGLI,EORC product,N3b,2019-01-05T00:00:00,90.190000,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,JAXA/EORC,JP04,Weekly,34.750000,136.700000
1091,"41.1017, -72.934",US,New York,"New York, Chl-a",AAOT fixed station,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,MODIS Aqua,MODISA L2 LAC OC,N3b,2019-01-04T17:30:00,23.400051,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,US04,Weekly,41.101700,-72.934000

In [23]:
df.loc[df['Country'] == "IT"]

,AOI,Country,Region,City,Site Name,Description,Method,EO Sensor,Input Data,Indicator code,Time,Measurement Value,Y axis,Indicator Name,Data Provider,AOI_ID,Update Frequency,latitude,longitude
1,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, Chl-a",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,Aqua MODIS,MODISA L2 LAC OC,N3b,2019-01-11T12:40:00,-43.211117,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,IT6,Weekly,45.314247,12.508055
3,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, Chl-a",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,Aqua MODIS,MODISA L2 LAC OC,N3b,2019-01-25T12:20:00,-27.113966,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,IT6,Weekly,45.314247,12.508055
6,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, Chl-a",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,Aqua MODIS,MODISA L2 LAC OC,N3b,2019-02-15T12:40:00,0.000000,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,IT6,Weekly,45.314247,12.508055
7,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, Chl-a",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,Aqua MODIS,MODISA L2 LAC OC,N3b,2019-02-22T11:40:00,-29.437669,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,IT6,Weekly,45.314247,12.508055
8,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, Chl-a",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean Chl-a concentration anomaly as pro...,Aqua MODIS,MODISA L2 LAC OC,N3b,2019-02-28T12:10:00,56.445046,Chlorophyll-a concentration anomaly [%],Chlorophyll-a concentration anomaly,NASA OBPG,IT6,Weekly,45.314247,12.508055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, SPM",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean SPM concentration anomaly as proxy...,Aqua MODIS,MODISA L2 LAC OC,N3b,2021-05-08T11:30:00,-5.303440,Total Suspended Matter concentration anomaly [%],Total Suspended Matter concentration anomaly,NASA OBPG,IT10,Weekly,45.314247,12.508055
1086,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, SPM",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean SPM concentration anomaly as proxy...,Aqua MODIS,MODISA L2 LAC OC,N3b,2021-05-15T11:30:00,-6.075185,Total Suspended Matter concentration anomaly [%],Total Suspended Matter concentration anomaly,NASA OBPG,IT10,Weekly,45.314247,12.508055
1088,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, SPM",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean SPM concentration anomaly as proxy...,Aqua MODIS,MODISA L2 LAC OC,N3b,2021-05-29T11:30:00,23.156298,Total Suspended Matter concentration anomaly [%],Total Suspended Matter concentration anomaly,NASA OBPG,IT10,Weekly,45.314247,12.508055
1089,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, SPM",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean SPM concentration anomaly as proxy...,Aqua MODIS,MODISA L2 LAC OC,N3b,2021-06-05T11:30:00,8.460702,Total Suspended Matter concentration anomaly [%],Total Suspended Matter concentration anomaly,NASA OBPG,IT10,Weekly,45.314247,12.508055
1090,"45.314247, 12.508055",IT,North Adriatic Sea,"Venice, SPM",AAOT fixed station Venezia,Water Quality Time Series,Weekly mean SPM concentration anomaly as proxy...,Aqua MODIS,MODISA L2 LAC OC,N3b,2021-06-12T11:30:00,26.138255,Total Suspended Matter concentration anomaly [%],Total Suspended Matter concentration anomaly,NASA OBPG,IT10,Weekly,45.314247,12.508055